databases:
  - name: sistem-pkl-db
    databaseName: sistem_pkl
    user: sistem_pkl
    plan: starter

services:
  - type: web
    name: sistem-pkl
    runtime: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /up
    dockerfilePath: ./Dockerfile
    disk:
      name: sistem-pkl-storage
      mountPath: /var/www/html/storage
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: Sistem PKL
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://sistem-pkl.onrender.com
      - key: ASSET_URL
        value: https://sistem-pkl.onrender.com
      - key: APP_TIMEZONE
        value: Asia/Jakarta
      - key: APP_LOCALE
        value: id
      - key: APP_FALLBACK_LOCALE
        value: id
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: sistem-pkl-db
          property: connectionString
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: RUN_MIGRATIONS
        value: true
